config/routes.rb
Auth::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  root to: "sessions#new"
  get 'sessions/customer'
  get 'sessions/index'
  get 'sessions/show'
  get 'sessions/enter'
  get 'sessions/delete_page'
  get 'sessions/delete_account'
  get 'vendors/home'
  get 'vendors/edit'
  get 'vendors/upload_page'
  get 'vendors/viewCodes'
  get 'vendors/profile'
  get 'vendors/remove_codes'
  get 'vendors/change_to_user'
  get 'vendors/clear_history'
  get 'sessions/change_to_vendor'
  get 'admin/login'

  get 'vendors/new'


  get 'providers/index'
  get 'providers/home'
  get 'providers/edit'
  get 'providers/upload_page'
  get 'providers/remove_codes'
  get 'providers/clear_history'


  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/logout", to: "sessions#destroy", :as => "logout"
  match "/logout", to: "vendors#destroy", :as => "logout2"
  resources :sessions
  resources :users do
    resources :vendorcodes
    resources :provider
  end

  
  resources :vendors do
    collection {post :import}
    collection {post :update_profile}
    resources :vendorcodes
  end


  resources :providers do
    collection {post :import2}
    collection {post :update_profile}
    resources :providercodes
  end
  ActiveAdmin.routes(self)
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base 
	# require 'csv'
	has_many :vendorCodes
	attr_accessible :history, :provider, :email, :name , :description, :instruction, :website, :comment , :helpLink, :expiration, :cashValue, :usedCodes, :uploadedCodes, :unclaimCodes, :removedCodes
	before_create :defaultValue

	def defaultValue
		self.usedCodes = 0
		self.uploadedCodes = 0
		self.unclaimCodes = 0
		self.removedCodes = 0
		self.cashValue = "0.00"
	end


  	def self.import(file, current, comment, type)
  		numberOfCodes = 0
  		date = ""
    	f = File.open(file.path, "r")
		f.each_line do |row|
			row = row.gsub(/\s+/, "")  # 12 3 4 --> 1234, 
			if row !=  ""   # don't get any blank code
				if type == "vendor"	
			      	a = current.vendorCodes.create!(:code => row, :name => current.name , :vendor => current)
			   
			    else
			    	a = current.providerCodes.create!(:code => row, :name => current.name , :provider => current)
			    end
			    numberOfCodes = numberOfCodes + 1
		    end
		end # end CSV.foreach
		f.close
		history = current.history
		
	    date = Time.now.to_formatted_s(:long_ordinal)
	    if history == nil
	    	history = "#{date}+++++#{comment}+++++#{numberOfCodes.to_s}|||||"
	    else
	    	history = "#{history}#{date}+++++#{comment}+++++#{numberOfCodes.to_s}|||||"
	    end
	    current.update_attribute(:history, history)
	    current.update_attribute(:uploadedCodes, current.uploadedCodes + numberOfCodes)
	    current.update_attribute(:unclaimCodes, current.unclaimCodes + numberOfCodes)


  	end # end self.import(file)


  	def self.update_profile_vendor(current_vendor,info)
  		current_vendor.update_attributes(:cashValue => info["cashValue"], :expiration => info["expiration"], :helpLink => info["helpLink"],:instruction => info["instruction"], :description => info["description"])
  	end # end self.profile()

  	def self.remove_unclaimed_codes(current, type)
  		unclaimed = ""
  		if type == "vendor"
  			unclaimedCodes=current.vendorCodes.where(:user_id => nil)
  		else
  			unclaimedCodes=current.providerCodes.where(:user_id => nil)
  		end

  		num = current.unclaimCodes
  		date = Time.now.to_formatted_s(:long_ordinal)

  		history = current.history
  		history = "#{history}#{date}+++++Delete Codes+++++-#{num.to_s}|||||"
  		current.update_attribute(:history, history)

  		contents = "There're #{num} unclaimed codes, remove on #{date}\n\n"
  		unclaimedCodes.each do |code|
  			contents = "#{contents}#{code.code}\n"
  			code.destroy
  		end
  		current.update_attribute(:unclaimCodes, 0)
  		current.update_attribute(:removedCodes, current.removedCodes + num)

  		return contents
  	end


  	def self.homeSet(histories)
		histories = histories.split("|||||")

		histories_array=[]
		histories.each do |history|
			temp = history.split("+++++")
			histories_array.push(temp)
		end
		histories_array.reverse!

	    return histories_array
  	end

  

end

app/controllers/vendors_controller.rb
require 'rubygems'
require 'google_chart'

class VendorsController < ApplicationController

  def index
    # @vendor = Vendor.find(session[:vendor_id])
  end
# --------------------------
  def import
    if params[:file].nil?
      redirect_to '/vendors/upload_page', :flash => { :error => "You have not upload a file" }
    else
      current_vendor=Vendor.find(session[:vendor_id])
      Vendor.import(params[:file], current_vendor,params[:comment], "vendor")
      redirect_to '/vendors/home', notice: "Codes imported"
    end
  end


# ---------------
  def home
    @vendor = Vendor.find(session[:vendor_id])

    @histories_array = []
    if @vendor.history != nil
      @histories_array = Vendor.homeSet(@vendor.history)
    end

    @hash = {"uploaded" => @vendor.uploadedCodes,"used" => @vendor.usedCodes, "unclaim" => @vendor.unclaimCodes, "removed" => @vendor.removedCodes }
    gon.codes = @hash
    gon.history = @vendor.history

  end


  def upload_page
    @vendor = Vendor.find(session[:vendor_id])
    @vendorcodes= @vendor.vendorCodes.all
  end


  def profile
    @vendor = Vendor.find(session[:vendor_id])
    @vendorcodes = @vendor.vendorCodes.all
  end

  def update_profile
    current_vendor=Vendor.find(session[:vendor_id])
   
    @info = {}
    cash = params[:cashValue]
    cash = cash.gsub(/\s+/, "")
    @info["cashValue"] = cash

    @info["instruction"] = params[:instruction]
    @info["description"] = params[:description]
    @info["helpLink"] = params[:helpLink]
    @info["expiration"] = params[:expiration]

    Vendor.update_profile_vendor(current_vendor,@info)
    redirect_to '/vendors/home', notice: "Profile Updated"
  end

  def remove_codes   #:usedCodes, :uploadedCodes, :totalCodes, :unclaimCodes, :removedCodes
    current_vendor=Vendor.find(session[:vendor_id])
    flag = current_vendor.vendorCodes.where(:user_id => nil)
    if flag.count == 0
      redirect_to '/vendors/home', :flash => { :error => "There's No Unclaimed Codes" }
    else
      contents = Vendor.remove_unclaimed_codes(current_vendor,"vendor")
      send_data contents,  :filename => "Unclaimed_Codes.txt" 
    end
  end


  def clear_history
    current_vendor=Vendor.find(session[:vendor_id])
    if current_vendor.history.nil?
      redirect_to '/vendors/home', :flash => { :error => "History is empty" }
    else  
      current_vendor.update_attribute(:history, nil)
      redirect_to '/vendors/home', notice: "Cleared History"
    end
  end

  def change_to_user
    current_vendor=Vendor.find(session[:vendor_id])
    current_user=User.find_by_provider_and_email(current_vendor.provider, current_vendor.email)
    if current_user.nil?
     current_user =  User.create!(:provider => current_vendor.provider, :name => current_vendor.name, :email => current_vendor.email)
    end
    session[:user_id]=current_user.id
    if current_user.code == nil 
      redirect_to '/sessions/new', notice: "Changed to user account"
    else
      redirect_to '/sessions/customer', notice: "Changed to user account"
    end
  end



end

app/views/vendors/edit.html.erb
<h1>Vendor#edit Hello</h1>

app/views/vendors/home.html.erb
<p class="account"><%= t 'vendor.login' %><%= @vendor.provider.upcase  %> | <%= t 'vendor.name' %> <%= @vendor.name %> | <%= link_to "Logout", logout_path, :id => "logout" %></p>
<div id="welcome">

    <h1> <%= image_tag('logo.png', :size => '400x100', :class => 'logo' ) %></h1>
  </div>

<% if flash[:error] != nil %>
<div class = "warning">
    <% flash.keys.each do |k| %> 
       <center><font color="black"><%= flash[k] %></font></center>
    <% end %> 
</div>
<br>
<% end %>

    


<% if flash[:notice] != nil %>
<div class = "notice">
    <% flash.keys.each do |k| %> 
       <center><font color="black"><%= flash[k] %></font></center>
    <% end %> 
</div>
<br>
<% end %>

<center><div id="barchart_values" style="width: 900px; height: 150px;"></div></center>

<br>
<br>
<br>
<br>





<div class = "group-buttons">
<div class = "row1">
   <%= link_to "Login as a user", '/vendors/change_to_user', {:id => "user-login", :style => 'color:#000'} %>
</div>

<div class = "row1">
   <%= link_to "Upload New Codes", '/vendors/upload_page', {:id => "upload", :style => 'color:#000'} %>
</div>
<div class = "row1">
   <%= link_to "Update Your Profile", '/vendors/profile', {:id => "update-profile", :style => 'color:#000'} %>
</div>


  <%= link_to "Download And Remove Unclaimed Codes", '/vendors/remove_codes', {:id => "remove-unclaimed-codes" , :style => 'color:#000'} %>
<!-- <div class = "button_confirm">
 <button onclick="confirmation()" id="remove-unclaimed-codes" color = "#000" > Download And Remove Unclaimed Codes</button> 
</div> -->

</div>



<br>
   
<h4 class="history"><%= t 'vendor.history' %></h4>

<center><%= link_to "Clear History", '/vendors/clear_history', {:id => "clear-history", :style => 'color:#000'} %></center>
<!-- <div class = "button_vendor">

<button class = "button_confirm" id="clear-history" onclick="confirmation2()">Clear History</button>

</div> -->




<div class = "vendor_table">

<table>

    <tr class = "vendor_header">
      <td width = "25%"><%= t 'vendor.col1' %></td>
      <td width = "50%"><%= t 'vendor.col2' %></td>
      <td width = "25%"><%= t 'vendor.col3' %></td>
    </tr>
  
<tbody>
  
    <% @histories_array.each do |history| %>
      <tr class="<%= cycle('evenn', 'oddd') -%>">
        <td width = "20%"><%= history[0] %></td>
        <td width = "60%" id="descriptions"><%= history[1] %></td>
        <td width = "20%"><%= history[2] %></td>
      </tr>

    <% end %>
  </tbody>
</table>
</div>



<html>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
 <script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
    google.setOnLoadCallback(drawChart);
    function drawChart() {
      var data = google.visualization.arrayToDataTable([
        ["Element", "Quantity", { role: "style" } ],
        ["Uploaded", gon.codes["uploaded"], "#080dcc"],
        ["Used", gon.codes["used"], "#c53711"],
        ["Unclaimed", gon.codes["unclaim"], "#0c9200"],
        ["Removed", gon.codes["removed"], "color: #000000"]

      ]);

      var view = new google.visualization.DataView(data);
      view.setColumns([0, 1,
                       { calc: "stringify",
                         sourceColumn: 1,
                         type: "string",
                         role: "annotation" },
                       2]);

      var options = {
        title: "Codes Data",
        width: 400,
        height: 200,
        bar: {groupWidth: "95%"},
        legend: { position: "none" },
      };
      var chart = new google.visualization.BarChart(document.getElementById("barchart_values"));
      chart.draw(view, options);
  }


  function confirmation() {
    if (gon.codes["unclaim"] == 0) {
      alert("you have no unclaimed code to remove");
    } 
    else {
      var answer = confirm("Do you want to remove " + gon.codes["unclaim"] + " unclaimed codes?")
      unclaim = gon.codes["unclaim"]
      if (answer){
        window.location = "/vendors/remove_codes";
        alert(unclaim + " unclaimed codes have been removed");
        window.location = "/vendors/home";
      }
    }
  }


  function confirmation2() {
    if (gon.history == null) {
      alert("You have no history");
    } 
    else {
      var answer = confirm("All the histories will be removed\n\n\t     Are you sure?")
      if (answer) {
        window.location = "/vendors/clear_history"
      }
    }
  }

  </script>

</html>

app/views/vendors/index.html.erb
<h1>Session#index Hello</h1>

app/views/vendors/new.html.erb
<% if current_user %>
  <h1>Redeem your code</h1>
  <p>
    <strong>Name:</strong>
    <%= current_user.name %>
   
  </p>
  <p>
    <strong>Provider:</strong>
    <%= current_user.provider %>
  </p>
  <p>
    <strong>OmniAuth UID:</strong>
    <%= current_user.uid %>
  </p>

  


  <form action="sessions#show" method="POST">
    <p>
    <label for="task_name"><strong>Enter your code Here:</strong></label><br />
      <%= text_field :code , :size => 20 %>
    </p>
    <input type="submit">
  </form>




  <p><%= link_to "Log out", logout_path %></p>


<% else %>
  <strong><h1>Welcome to Redeemify, Vendor</h1></strong>


  <p><strong>Please Sign in through one of these services:</strong></p>

  <div class="auth_providers">
    <a href="/auth/google_oauth2" class="auth_provider">
      <%= image_tag "google_apps_64.png", size: "64x64", alt: "Google" %>
      Google
    </a>
    <a href="/auth/facebook" class="auth_provider">
      <%= image_tag "facebook_64.png", size: "64x64", alt: "Facebook" %>
      Facebook
    </a>
    <a href="/auth/twitter" class="auth_provider">
      <%= image_tag "twitter_64.png", size: "64x64", alt: "Twitter" %>
      Twitter
    </a>

    <a href="/auth/github" class="auth_provider">
      <%= image_tag "github_64.png", size: "64x64", alt: "Github" %>
      GitHub
    </a>

    <a href="/auth/amazon" class="auth_provider">
      <%= image_tag "amazon_64.png", :size => "64x64", :alt => "amazon" %>
      Amazon
    </a>

    <%= link_to "Back", new_session_path %>

  </div>
<% end %>

app/views/vendors/profile.html.erb
<p class="account"><%= t 'vendor.login' %><%= @vendor.provider.upcase  %> | <%= t 'vendor.name' %> <%= @vendor.name %> | <%= link_to "Logout", logout_path, :id => "logout" %></p>
<div id="welcome">

    <h1> <%= image_tag('logo.png', :size => '400x100', :class => 'logo' ) %></h1>
</div>


<h4 class="loginwith3"><%= t 'editprofile.header' %></h4>  <%= form_tag update_profile_vendors_path, multipart: true do %>

    <div class = "home1">
 <p class="homee"><%= link_to image_tag('home2.png', :size =>'40x40'), '/vendors/home' %></p>
</div>

<% if flash[:error] != nil %>
<br>
    <% flash.keys.each do |k| %> 
       <center><font color="red"><%= flash[k] %></font></center>
    <% end %> 
<% end %>


    <h3 class="upload_text" ><%= t 'editprofile.cashvalue' %><span id='question'>?</span></h3> 
    <textarea name="cashValue" id="cashValue" cols="8" rows="2"  ><%= @vendor.cashValue %></textarea>

    <h3 class="upload_text"><%= t 'editprofile.expiration' %><span id='question2'>?</span> </h3> 
    <% if @vendor.expiration == nil %>
    <input type="text" name="expiration" id="expiration"  cols="1" rows="1" placeholder = "mm/dd/yyyy"></input>
    <% else %>
    <input type="text" name="expiration" id="expiration"  cols="1" rows="1" value =<%= @vendor.expiration %>></input>
    <% end %>

    <h3 class="upload_text"><%= t 'editprofile.help' %><span id='question3'>?</span></h3> 
    <textarea name="helpLink" id = "helpLink" cols="50" rows="2"  ><%= @vendor.helpLink %></textarea>


    <h3 class="upload_text"><%= t 'editprofile.description' %><span id='question4'>?</span></h3> 
    <textarea name="description" id = "description" cols="50" rows="4"  ><%= @vendor.description %></textarea>

    <h3 class="upload_text"><%= t 'editprofile.instruction' %><span id='question5'>?</span></h3> 
    <textarea name="instruction" id="instruction" cols="50" rows="4" ><%= @vendor.instruction %></textarea>

    <br>
    <br>





  <div class = "submit">
    <%= submit_tag "SUBMIT", :id => "submit"%>
  <% end %>
  </div>
  <br>
  <br>
<div id='popup1'><%= t 'editprofile.popup1' %></div>
<div id='popup2'><%= t 'editprofile.popup2' %></div>
<div id='popup3'><%= t 'editprofile.popup3' %></div>
<div id='popup4'><%= t 'editprofile.popup4' %></div>
<div id='popup5'><%= t 'editprofile.popup5' %></div>
   <script>
    $(document).ready(function() {
    $('#question').hover(function() {
        $('#popup1').show();
    }, function() {
        $('#popup1').hide();
    });
});
    </script>
    <script>
    $(document).ready(function() {
    $('#question2').hover(function() {
        $('#popup2').show();
    }, function() {
        $('#popup2').hide();
    });
});
    </script>
    <script>
    $(document).ready(function() {
    $('#question3').hover(function() {
        $('#popup3').show();
    }, function() {
        $('#popup3').hide();
    });
});
    </script>
    <script>
    $(document).ready(function() {
    $('#question4').hover(function() {
        $('#popup4').show();
    }, function() {
        $('#popup4').hide();
    });
});
    </script>
    <script>
    $(document).ready(function() {
    $('#question5').hover(function() {
        $('#popup5').show();
    }, function() {
        $('#popup5').hide();
    });
});
    </script>


<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>jQuery UI Datepicker - Default functionality</title>

  <script>
  $(function() {
    $( "#expiration" ).datepicker();
  });
  </script>
</head>

</html>

app/views/vendors/show.html.erb
<h1>Hello Vendor</h1>
  <p><%= link_to "Logout", logout_path, id:"logout-link" %></p>

app/views/vendors/upload_page.html.erb
<p class="account"><%= t 'vendor.login' %><%= @vendor.provider.upcase  %> | <%= t 'vendor.name' %> <%= @vendor.name %> | <%= link_to "Logout", logout_path, :id => "logout" %></p>
<div id="welcome">

    <h1> <%= image_tag('logo.png', :size => '400x100', :class => 'logo' ) %></h1>
</div>

<% if flash[:error] != nil %>
<div class = "warning">
    <% flash.keys.each do |k| %> 
       <center><font color="black"><%= flash[k] %></font></center>
    <% end %> 
</div>
<br>
<% end %>

    


<% if flash[:notice] != nil %>
<div class = "notice">
    <% flash.keys.each do |k| %> 
       <center><font color="black"><%= flash[k] %></font></center>
    <% end %> 
</div>
<br>
<% end %>


 <h4 class="loginwith3"><%= t 'vendorupload.header' %></h4>
  <div class = "home1">
 <p class="homee"><%= link_to image_tag('home2.png', :size =>'40x40'), '/vendors/home' %></p>
</div>




<h3 class="upload_text"><%= t 'vendorupload.line1' %> </h3>  <%= form_tag import_vendors_path, multipart: true do %>
<p class = "upload_text"><%= t 'vendorupload.line2' %> </p>
<br>
    <div class = "upload_text">
    <%= file_field_tag :file %> 
    </div>
    <h3 class="upload_text"><%= t 'vendorupload.comment' %><span id='question'>?</span></h3> 
    <div id='popup6'> <%= t 'vendorupload.popup' %> </div>

    <textarea name="comment" id="comments" cols="50" rows="4" placeholder="Comment..."></textarea>

    <br>
    <br>




 

<div class="submit">
    <%= submit_tag "Submit", :id => "submit"%>
  <% end %>
</div>
</div>

 <script>
  $(function() {
    $( "#expiration" ).datepicker();
  });
  </script>
 <script>
    $(document).ready(function() {
    $('#question').hover(function() {
        $('#popup6').show();
    }, function() {
        $('#popup6').hide();
    });
});
    </script>

app/views/vendors/viewCodes.html.erb
<p>Account from: <%= @vendor.provider.upcase  %> | <%= @vendor.name %> | <%= link_to "Logout", logout_path, :id => "logout" %></p>
<div id="welcome">

    <h1> <%= image_tag('logo.png', :size => '100x100', :class => 'logo' ) %> REDEEMIFY</h1>
  </div>
<div class = "vendor">
    <h1>VENDOR</h1>
  </div>
  <div class = "upload_group">
  <div class = "upload_vendor">
<p class="vendor_name"><%= @vendor.name %></p>
</div>
</div>
<p class="backtohome"><%= link_to image_tag("home.jpg",size:"30x30"), '/vendors/home' %></p>
<div class="vendor_table">
<table >
  <thead class="header">
    <tr>
      <th class = "codes">Codes</th>
      <th>Expiration Date</th>
    </tr>
  </thead>
  <tbody>
    <% @vendorcodes.each do |vendorcode| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td class="codes"><%= vendorcode.code %></td>
        <td><%= vendorcode.expiration %></td>
      </tr>
    <% end %>
  </tbody>
</table>